import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import { Toaster } from '@/components/ui/sonner';
import { cn } from '@/lib/utils';
import Providers from '@/providers';
import { Navbar } from '@/components/layout/navbar';
import { getSession } from '@/lib/nextAuthConfig';

const font = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: {
    default: 'Create Next App',
    template: '%s | Create Next App',
  },
  description: 'Generated by create next app',
  openGraph: {
    title: 'Create Next App',
    description: 'Generated by create next app',
  },
  alternates: {
    canonical: '/',
  },
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL!),
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(font.className, 'antialiased')}>
        <Providers session={session}>
          <Navbar />
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
